name: FastAPI Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Render Deployment
        run: |
          echo "Triggering deployment..."
          curl -X POST "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -H "Accept: application/json"

      - name: Wait for Deployment to Complete
        run: |
          echo "Waiting for deployment to complete..."
          while true; do
            status_response=$(curl -X GET "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys" \
              -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
              -H "Accept: application/json")
            
            latest_status=$(echo $status_response | jq -r '.[0].status')
            echo "Current status: $latest_status"

            if [[ "$latest_status" == "build_failed" || "$latest_status" == "update_failed" || "$latest_status" == "pre_deploy_failed" ]]; then
              echo "Deployment failed with status: $latest_status"
              exit 1
            fi

            if [[ "$latest_status" == "live" ]]; then
              echo "Deployment successful!"
              break
            fi

            sleep 10  # Wait for 10 seconds before checking again
          done
